
#### Het meenemen, dragen, en eventueel kopen van gehoorscherming

In deze ronde zijn drie gedragingen uitgevraagd: oordopjes meenemen, oordopjes indoen, en oordopjes kopen als de muziek hard staat maar ze niet voorhanden zijn. De determinanten van deze drie gedragingen worden tegelijk besproken.

##### Determinantenstructuur

Intentie scores om gehoorbescherming mee te nemen en ook om deze te dragen waren hoog, met gemiddelden rond de zes (op een zevenpuntschaal), en de meeste scores zelfs rond de zeven. Dat suggereert dat de steekproef waarschijnlijk deels tot stand is gekomen via zelfselectie van deelnemers die al enthousiast zijn over gehoorbescherming. De intentie om gehoorbescherming te kopen als deze niet voorhanden was, was lager: deze lag gemiddeld onder de vier, met de meeste scores rond de een en twee. Zelfs onder deze deelnemers gold dus dat als gehoorbeschadiging werd vergeten, deze niet snel ter plekke werd gekocht.

Attitude om gehoorbescherming mee te nemen was relatief hoog (rond de zes), en waargenomen norm en gedragscontrole waren iets lager (rond de vijf). Deze drie hingen allemaal sterk samen met intentie, maar waargenomen norm het zwakst. Gerapporteerde gewoonte was wat lager, met een relatief inaccurate schatting waardoor zowel deze zowel onder de vier als boven de vijf zou kunnen zitten. Gewoonte hing ook iets minder sterk samen met intentie, maar de schatting was weer vrij inaccuraat. Het patroon voor het dragen (i.e. indoen) van gehoorbescherming was vrijwel hetzelfde.

Met betrekking tot het ter plekke kopen van gehoorbescherming is waargenomen norm juist de sterkste voorspeller van intentie, hoewel het verschil heel klein is. Alle vier de determinanten voorspellen intentie vrij goed. Gewoonte is nog lager dan bij de andere twee gedragingen, wat logisch is gegeven de verschillende soorten gedrag (i.e. het kopen van gehoorbescherming is meer een 'one shot' gedrag).

##### Sub-determinanten (opvattingen) binnen attitude

Deelnemers vinden het wenselijk dat oordopjes goed zitten en een goede prijs-kwaliteit verhouding hebben. De meeste deelnemers vinden het onwenselijk om de muziek zachter te horen, maar degenen die dit wenselijk vinden hebben wel een hogere attitude en intentie om gehoorbescherming mee te nemen. Of deelnemers het wenselijk vonden om meer van de muziek te genieten en te focusen hing niet samen met attitude of intentie, maar het gegeven dat de meeste deelnemers aangaven dit wenselijk te vinden kan wellicht nog steeds gebruikt worden in preventieboodschappen. Deelnemers vonden het onwenselijk om last te hebbben van mensen die hard praten; dit is dus een sterk argument voor het dragen van gehoorbescherming. Deelnemers vonden het ook onwenselijk om hun gehoor te beschadigen of de dag na het uitgaan een piep in hun oren te horen.

Het was interessant dat of deelnemers het wenselijk of onwenselijk vonden om de muziek verstoord te horen, helemaal niet samenhing met attitude en intentie. Dit lijkt niet consistent met de waarde die veel bezoekers aan muziekbeleving lijken te hechten.

##### Sub-determinanten (opvattingen) binnen waargenomen norm

Deelnemers gaven aan dat hun sociale omgeving heel positief stond tegenover het meenemen en dragen van gehoorbescherming. De descriptieve norm gaf aan de perceptie van of sociale referenten zelf gehoorbescherming meenamen en gebruikten, veel meer spreiding toonden. Oftewel: de deelnemers hadden de indruk dat iedereen in principe voorstanden was van gehoorbescherming, maar die zelf niet altijd consequent gebruikte. Descriptieve normen hingen sterker samen met waargenomen norm en intentie dan injunctieve normen (i.e. waargenomen goed- of afkeuring), maar dit kan ook een gevolg zijn van de linksscheven verdeling van de injunctieve norm. Hoe dan ook impliceren de sterke positieve normen dat het bespreekbaar maken van gehoorbescherming goed kan werken om deze normen te versterken en bekrachtigen. Met betrekking tot het kopen van gehoorbescherming zijn de patronen hetzelfde.

##### Sub-determinanten (opvattingen) binnen waargenomen gedragscontrole

Hoe makkelijker deelnemers het vonden om er op tijd aan te denken oordopjes mee te nemen was een sterke voorspeller van hun waargenomen gedragscontrole en intentie. Herinneringen kunnen dus goed helpen om te zorgen dat deelnemers gehoorbescherming meenemen.

Ook met betrekking tot het tijdig indoen van gehoorbescherming lijken herinneringen kansrijk: ook hier maakt het uit hoe makkelijk deelnemers het vinden om er op tijd aan te denken. Dit geldt ook voor hoe makkelijk deelnemers het vinden om te herkennen wanneer de muziek zo hard staat dat oordopjes nodig zijn.

Tot slot geven deelnemers aan dat alcoholgebruik de kans op het gebruik of de aankoop van gehoorbescherming verlaagt. Het lijkt dus verstandig om herinneringen te plaatsen bij de ingang van feesten, zodat deelnemers hun oordopjes hopelijk al indoen als ze nog nuchter zijn, bijvoorbeeld als ze staan te wachten om binnen te komen.
